In [31]:
import numpy as np

In [32]:
a = np.array([
    [3, 3, 3],
    [1, 3, 4],
    [7, 1, 3]
])
b = np.array([3, 3, 3, 1, 3, 4, 7, 1, 3])

In [33]:
np.unique(a)


array([1, 3, 4, 7])

In [34]:
np.unique(b)

array([1, 3, 4, 7])

In [39]:
z = np.array([92, 13, 44, 555, 1, -3])
z = np.flip(z)

In [40]:
z[4]

13

In [45]:
vec1 = np.ones(5)
vec2 = 2*np.ones(5)
print(vec1, vec2)

[1. 1. 1. 1. 1.] [2. 2. 2. 2. 2.]


In [46]:
res = vec1.dot(vec2)
res

10.0

In [47]:
m1 = np.array([
    [0, 9, 19, 13],
    [1, 20, 5, 13],
    [12, 11, 3, 4]
])
m2 = np.array([
    [2, 0, 0, 0],
    [1, 2, 2, 0],
    [2, 1, 1, 0],
    [0, 0, 1, 1]
])

res = m1.dot(m2)
res

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [49]:
for i in range(len(res)):
    print(res[i, i])

47
45
29


In [50]:
np.mean(np.array([
    [-1, 33, 4, 1],
    [0, 1, 1, 0]
]))

4.875

In [51]:
np.linalg.det(np.array([
    [6, 0, 3],
    [0, -1, 2],
    [12, 3, 0]
]))

-1.9984014443252774e-15

In [52]:
eigenvalues, eigenvecs = np.linalg.eig(np.array([
    [1, -1, -1, 0],
    [-1, 2, -1, -1],
    [-1, -1, 2, -1],
    [0, -1, -1, 1]
]))
print(eigenvalues)

[-1.  1.  3.  3.]


In [54]:
res = np.linalg.inv(np.array([
    [2, 4, 0, 4, 1],
    [2, 4, 1, 1, 0],
    [1, 1, 1, 2, 2],
    [0, 1, 3, 2, 4],
    [2, 2, 2, 0, 2]
]))
sum = 0
for i in range(len(res)):
    sum += res[i, i]

sum    

2.6999999999999993